<a href="https://colab.research.google.com/github/vishnudas-1212/machine-learning/blob/main/Naive__bayes(flu_dataset)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
df=pd.read_csv("/content/naivebayes.csv")

In [4]:
df

Chills runny nose head ache fever Flu
0      Y          N      Mild     Y   N
1      Y          Y        No     N   Y
2      Y          N    Strong     Y   Y
3      N          Y      Mild     Y   Y
4      N          N        No     N   N
5      N          Y    Strong     Y   Y
6      N          Y    Strong     N   N
7      Y          Y      Mild     Y   Y

In [5]:
x=df.iloc[:,:-1]

In [6]:
x

Chills runny nose head ache fever
0      Y          N      Mild     Y
1      Y          Y        No     N
2      Y          N    Strong     Y
3      N          Y      Mild     Y
4      N          N        No     N
5      N          Y    Strong     Y
6      N          Y    Strong     N
7      Y          Y      Mild     Y

In [7]:
y=df.iloc[:,-1]

In [8]:
y

0    N
1    Y
2    Y
3    Y
4    N
5    Y
6    N
7    Y
Name: Flu, dtype: object

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
label=LabelEncoder()

In [14]:
x1=x.apply(label.fit_transform)

In [15]:
x1

Chills  runny nose  head ache  fever
0       1           0          0      1
1       1           1          1      0
2       1           0          2      1
3       0           1          0      1
4       0           0          1      0
5       0           1          2      1
6       0           1          2      0
7       1           1          0      1

In [17]:
y1=label.fit_transform(y)

In [18]:
y1

array([0, 1, 1, 1, 0, 1, 0, 1])

In [19]:
from sklearn.naive_bayes import GaussianNB

In [20]:
model=GaussianNB()

In [21]:
model.fit(x1,y1)

GaussianNB(priors=None, var_smoothing=1e-09)

In [22]:
y_pred=model.predict(x1)

In [23]:
y_pred

array([1, 1, 1, 1, 0, 1, 0, 1])

In [24]:
pd.DataFrame(data=[y1,y_pred])

0  1  2  3  4  5  6  7
0  0  1  1  1  0  1  0  1
1  1  1  1  1  0  1  0  1

In [25]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report

In [26]:
confusion_matrix(y1,y_pred)

array([[2, 1],
       [0, 5]])

In [28]:
accuracy_score(y1,y_pred)*100

87.5

In [29]:
recall_score(y1,y_pred)

1.0

In [30]:
precision_score(y1,y_pred)

0.8333333333333334

In [31]:
f1_score(y1,y_pred)


0.9090909090909091

In [33]:
print(classification_report(y1,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.83      1.00      0.91         5

    accuracy                           0.88         8
   macro avg       0.92      0.83      0.85         8
weighted avg       0.90      0.88      0.87         8

