<a href="https://colab.research.google.com/github/vishnudas-1212/machine-learning/blob/main/Naive_bayes__algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [59]:
df=pd.read_csv('/content/play.csv')

In [60]:
df

Outlook   Temp  Humidity   Windy  Play
0      Rainy    Hot      High   False    No
1      Rainy    Hot      High    True    No
2   Overcast    Hot      High   False   Yes
3      Sunny   Mild      High   False   Yes
4      Sunny   Cool    Normal   False   Yes
5      Sunny   Cool    Normal    True    No
6   Overcast   Cool    Normal    True   Yes
7      Rainy   Mild      High   False    No
8      Rainy   Cool    Normal   False   Yes
9      Sunny   Mild    Normal   False   Yes
10     Rainy   Mild    Normal    True   Yes
11  Overcast   Mild      High    True   Yes
12  Overcast    Hot    Normal   False   Yes
13     Sunny   Mild      High    True    No

In [61]:
X=df.iloc[:,:-1]

In [62]:
X

Outlook   Temp  Humidity   Windy
0      Rainy    Hot      High   False
1      Rainy    Hot      High    True
2   Overcast    Hot      High   False
3      Sunny   Mild      High   False
4      Sunny   Cool    Normal   False
5      Sunny   Cool    Normal    True
6   Overcast   Cool    Normal    True
7      Rainy   Mild      High   False
8      Rainy   Cool    Normal   False
9      Sunny   Mild    Normal   False
10     Rainy   Mild    Normal    True
11  Overcast   Mild      High    True
12  Overcast    Hot    Normal   False
13     Sunny   Mild      High    True

In [63]:
y=df.iloc[:,-1]

In [64]:
y

0       No
1       No
2      Yes
3      Yes
4      Yes
5       No
6      Yes
7       No
8      Yes
9      Yes
10     Yes
11     Yes
12     Yes
13      No
Name:  Play, dtype: object

In [65]:



df.isna().sum()   #checking missing values

Outlook      0
 Temp        0
 Humidity    0
 Windy       0
 Play        0
dtype: int64

In [66]:
#converting categorical to numerical data
#pre processing x and y


from sklearn.preprocessing import LabelEncoder

In [67]:
label=LabelEncoder()     #initializing the model

In [68]:
label

LabelEncoder()

In [69]:
X1= X.apply(label.fit_transform)    #converting to numerical data

In [70]:
X1

Outlook   Temp   Humidity   Windy
0         1      1          0       0
1         1      1          0       1
2         0      1          0       0
3         2      2          0       0
4         2      0          1       0
5         2      0          1       1
6         0      0          1       1
7         1      2          0       0
8         1      0          1       0
9         2      2          1       0
10        1      2          1       1
11        0      2          0       1
12        0      1          1       0
13        2      2          0       1

In [71]:
X.Outlook=label.fit_transform(X.Outlook)  #converting the single column

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:5170: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [72]:
X.Outlook

0     1
1     1
2     0
3     2
4     2
5     2
6     0
7     1
8     1
9     2
10    1
11    0
12    0
13    2
Name: Outlook, dtype: int64

In [73]:
y1=label.fit_transform(y)

In [74]:
y1

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [75]:
#import sklearn package

from sklearn.naive_bayes import GaussianNB

In [76]:
model=GaussianNB()

In [77]:
model

GaussianNB(priors=None, var_smoothing=1e-09)

In [78]:
model.fit(X1,y1)

GaussianNB(priors=None, var_smoothing=1e-09)

In [79]:
y_pred=model.predict(X1)

In [80]:
y_pred

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [ ]:
m=pd.DataFrame({'actual':y1,'predicted':y_pred})

In [81]:
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,f1_score

In [82]:
confusion_matrix(y1,y_pred)

array([[4, 1],
       [1, 8]])

In [83]:
pd.crosstab(y1,y_pred)

col_0  0  1
row_0      
0      4  1
1      1  8

In [84]:
accuracy_score(y1,y_pred)

0.8571428571428571

In [85]:
recall_score(y1,y_pred)

0.8888888888888888

In [86]:
f1_score(y1,y_pred)

0.8888888888888888